config/routes.rb
Rails.application.routes.draw do
  get 'invoices/index'
  resources :invoices do
  collection do
    get 'download_pdf'
  end
  end
  resources :customers
  root 'customers#index'
 
  

end

app/models/acceptance.rb
class Acceptance < ActiveRecord::Base
has_one :invoice
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :customer
	validates :item_name, presence: true,
                    length: { minimum: 5 }

                    
end

app/controllers/acceptances_controller.rb
class AcceptancesController < ApplicationController
	def index
    	@аcceptances = Acceptances.all
    	
     	  	end
	
	def show
	    @аcceptances = Acceptances.find(params[:id])
 		@customers = Customer.find(params[:id])
	    respond_to do |format|
	      format.html
	      format.pdf do
	      
        	render :pdf => "аcceptance", :аcceptances => 'show.pdf.slim', encoding: "UTF-8" 
	      end
	    end

  	end
  	def new
 		@аcceptances = Acceptances.new
 	end
	

	def create
  		@аcceptances = Acceptances.new(аcceptances_params)
  		
   		if @аcceptances.save
  			redirect_to @аcceptances
  		else
	    render 'new'
	  	end
	end


	def destroy
	  @аcceptances = Acceptances.find(params[:id])
	  @аcceptances.destroy
	 
	  redirect_to аcceptances_path
	end

	private
  	def аcceptances_params
    	params.require(:аcceptances).permit(:status, :invoice_id)
  	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :load_customers, only: [:show, :edit]

	def index
    	@customers = Customer.all
  	end
	
	def show
  	end
  	def new
 		@customers = Customer.new
 	end
	def edit
	end

	def create

  		

  		@customers = Customer.new(customers_params)
   		if @customers.save
  			redirect_to @customers
  		else
	    render 'new'
	  	end
	end

	def update
	  	@customers = Customer.find(params[:id])
		if @customers.update(customers_params)
		  redirect_to @customers
		else
		   render 'edit'
		end
	end
	def destroy
	  @customers = Customer.find(params[:id])
	  @customers.destroy
	 
	  redirect_to customers_path
	end

	private
	def load_customers
		@customers = Customer.find(params[:id])
	end
  	def customers_params
    	params.require(:customer).permit(:client, :client_name_tel, :client_inn,:client_kpp, :client_adress, :client_site, :client_tel, :client_email, :client_ogrn, :client_ks, :client_rs, :client_bik, :client_bank)
  	end


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	def index
    	@invoice = Invoice.all
    	
    end
	
	def show
		@invoice = Invoice.find(params[:id])
		  respond_to do |format|
	      format.html

	      format.pdf do
	      
        	render :pdf => "invoice", :invoice => 'show.pdf.slim', encoding: "UTF-8" 
	      end
	    end

  	end

  	def new
 		@invoice = Invoice.new
 	end
	
	def edit
	  	@invoice = Invoice.find(params[:id])
	end


	def create
		@invoice = Invoice.new(invoice_params)
	  		if @invoice.save
	  		redirect_to @invoice
	  		else
	    render 'new'
	  	end
	end

	def update
	  	@invoice = Invoice.find(params[:id])
		if @invoice.update(invoice_params)
		  redirect_to @invoice
		else
		   render 'edit'
		end
	end
	def destroy
	  @invoice = Invoice.find(params[:id])
	  @invoice.destroy
	 
	  redirect_to invoices_path
	end

	private
  	def invoice_params
    	params.require(:invoice).permit(:customer_id, :item_name, :unit, :price, :price_total)
  	end


end

app/helpers/acceptances_helper.rb
module AcceptancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/views/acceptances/index.html.slim
= link_to 'Новый акт', new_аcceptance_path 


h1 Акты

table.table-hover
	
		tr.head

		 	td Клиент
		 	td Номер акта
		 	td Дата
		 	td Сумма
		 	td
		 	td
			
		tr.client 
		 - @аcceptances.each do |аcceptance|
		 
		 	tr    			 
			 	td 
			 	td = аcceptance.id
			 	td = аcceptance.created_at.strftime("%d/%m/%Y")
			 	td = аcceptance.price_total
			 	td = link_to 'Показать', invoice_path(аcceptance)
			 	td = link_to 'Cкачать', invoice_path(аcceptance, :format => 'pdf')
			 	td = link_to 'Изменить', edit_invoice_path(аcceptance)
			 	td = link_to 'Удалить', invoice_path(аcceptance), method: :delete, data: { confirm: 'Уверены?' }
  


		 	

app/views/acceptances/show.html.slim
table width="772"
              
		            

        tr
          	td
            	h3 Акт выполенных работ № #{@аcceptance.id} от #{@аcceptance.created_at.strftime("%d/%m/%Y")}
            	
        
      
        

        tr 
        	td &nbsp;

        tr
          	td
            	table
            		
	                	                    
	                	tr
	                    	td width="750" Покупатель: #{@customers.client}, ИНН: #{@customers.client_inn}, КПП: #{@customers.client_kpp}, ОГРН: #{@customers.client_ogrn}, Адрес: #{@customers.client_adress}
	                    

       

        tr
          	td
            	table.table-bordered
            		

	                tr
	                    td width="20" №
	                    td width="340" Наименование товара
	                    td width="60" Единица изме-рения
	                    td width="50" Коли-чество
	                    td width="120" Цена
	                    td width="120" Сумма
	                tr
	                    td 1
	                    td = @invoice.item_name
	                    td усл.
	                    td = @invoice.unit
	                    td = @invoice.price
	                    td = @invoice.price_total
                

	                tr
	                    td.text-right colspan="5" Итого:
	                    td.border#text-right = @invoice.price_total
	                tr
	                    td.text-right colspan="5"Без налога (НДС)
	                    td.border#text-right -
	                tr
	                    td.text-right colspan="5" Всего к оплате:
	                    td.border#text-right #{@invoice.price_total}  
                
            

        tr
        	td &nbsp;

        tr
          	td Всего наименований 1, на сумму #{@invoice.price_total}           
          	

        tr
        	td #{RuPropisju.rublej(@invoice.price_total).mb_chars.capitalize}  00 коп.
        tr
        	td &nbsp;

        tr
          	td Выполнил_____________________ (Бунтов А.И.)
         
          	td Прянял_____________________ (#{@customers.client})
       tr
          	td МП
         
          	td МП
      

app/views/customers/_form.html.slim
= form_for @customers do |f|

	- if @customers.errors.any?
	#error_explanation
	h2 #{pluralize(@customers.errors.count, "error")} prohibited this customers from being saved
	    	 
	ul  
	- @customers.errors.full_messages.each do |msg|
	   	li  #{msg}
	    

	h2 Информация о клиенте
	p Наименование:
	= f.text_field :client
	p Сайт:
	= f.text_field :client_site
	p Телефон контактного лица:
	= f.text_field :client_tel
	p Имя контактного лица:
	= f.text_field :client_name_tel
	p Email:
	= f.text_field :client_email

	h2 Реквизиты клиента


	p ИНН:
	= f.text_field :client_inn
	p КПП: 
	= f.text_field :client_kpp
	p ОГРН: 
	= f.text_field :client_ogrn
	p Адрес:
	= f.text_area  :client_adress

	p Кор счет:
	= f.text_field :client_ks
	p Расчетный счет:
	= f.text_field :client_rs 
	p БИК:
	= f.text_field :client_bik
	p Наименование банка:
	= f.text_area :client_bank
	
	= f.submit 

app/views/customers/edit.html.slim
h1 Клиент № #{@customers.client}
= render 'form'

.btn = link_to 'Вернуться', customers_path

app/views/customers/index.html.slim
= link_to 'Новый клиент', new_customer_path 


h1 Клиенты

table.table-hover
	
		tr.head

		 	td Клиент
		 	td Телефон
		 	td Email
		 	td Сайт
		 	
			
		tr.client 
		 - @customers.each do |customer|	
		 	tr
			 	td = customer.client
			 	td = customer.client_tel
			 	td = customer.client_email
			 	td = customer.client_site
			 	td = link_to 'Новый счет', new_invoice_path
			 	td = link_to 'Показать', customer_path(customer)
			 	td = link_to 'Изменить', edit_customer_path(customer)
			 	td = link_to 'Удалить', customer_path(customer), method: :delete, data: { confirm: 'Уверены?' }
  


		 	

app/views/customers/new.html.slim
h1  Новый клиент

= render 'form'

.btn = link_to 'Вернуться', customers_path

app/views/customers/show.html.slim
h1 Клиент № #{@customers.client}

h2 Информация о клиенте

table.table-bordered
	tr 
		td Наименование
		td #{@customers.client}
	tr 	
		td Сайт
		td #{@customers.client_site}
	tr 	
		td Телефон контактного лица
		td #{@customers.client_tel}
	tr
		td Телефон контактного лица
		td #{@customers.client_name_tel}
		
	tr 	
		td Email
		td #{@customers.client_email}

h2 Реквизиты клиента

table.table-bordered

	tr 	
		td ИНН
		td #{@customers.client_inn}
	tr 
		td КПП 
		td #{@customers.client_kpp}
	tr 
		td ОГРН 
		td #{@customers.client_ogrn}
	tr
		td Адрес
		td #{@customers.client_adress}

	tr 
		td Кор счет
		td #{@customers.client_ks}
	tr
		td Расчетный счет
		td #{@customers.client_rs} 
	tr 
		td БИК
		td #{@customers.client_bik}
	tr 
		td Наименование банка
		td #{@customers.client_bank}

.btn = link_to 'Вернуться', customers_path

app/views/invoices/_form.html.slim
= form_for @invoice do |f|

	- if @invoice.errors.any?
	#error_explanation
	h2 #{pluralize(@invoice.errors.count, "error")} prohibited this invoice from being saved
	    	 
	ul  = @invoice.errors.full_messages.each do |msg|
	   	li  #{msg}
	    


	h2 Информация о клиенте
	p Наименование:
	= f.select(:customer_id, Customer.all.map {|c| [c.client, c.id]}) 
	= link_to 'Создать нового клиента', new_customer_path 
	
	table.table-bordered
		tbody
	  		tr.head
			    td Hаиминование услуги
			    td К-во			
			    td Цена
			    td Сумма
			    td
			    br
	    	tr.item
	    		td = f.text_field :item_name
	    		td = f.text_field :unit
	    		td = f.text_field :price
	    		td = f.text_field :price_total
	    		td.del
	    		br
			tr.total
	    		td 
	    		td 
	    		td Итого
	    		td
	    		td.total_price
	    		br

	= f.submit 

app/views/invoices/edit.html.slim
h1 СЧЕТ № #{@invoice.id} от #{@invoice.created_at.strftime("%d/%m/%Y")}
= render 'form'

.btn = link_to 'Вернуться', invoices_path

app/views/invoices/index.html.slim
= link_to 'Новый счет', new_invoice_path 


h1 Счета

table.table-hover
	
		tr.head

		 	td Клиент
		 	td Номер счета
		 	td Дата
		 	td Сумма
		 	td
		 	td
			
		tr.client 
		 - @invoice.each do |invoice|
		 
		 	tr    			 
			 	td 
			 	td = invoice.id
			 	td = invoice.created_at.strftime("%d/%m/%Y")
			 	td = invoice.price_total
			 	td = link_to 'Показать', invoice_path(customer_invoice)
			 	td = link_to 'Cкачать', invoice_path(customer_invoice, :format => 'pdf')
			 	td = link_to 'Изменить', edit_invoice_path(customer_invoice)
			 	td = link_to 'Удалить', invoice_path(customer_invoice), method: :delete, data: { confirm: 'Уверены?' }
  

		 	

app/views/invoices/new.html.slim
h1 Новый счет
= form_for :invoices, url: invoices_path do |f|
	p Номер 
	= f.number_field :num
	p Дата
	= f.date_field  :date
	h2 Информация о клиенте
	p Наименование:
	= f.text_field :client
	p ИНН:
	
	= f.text_field :client_inn
	p КПП: 
	= f.text_field :client_kpp
	p Адрес: 
	= f.text_area  :client_adress 
	p
	table.table-bordered
		tbody
	  		tr.head
			    td Hаиминование услуги
			    td К-во			
			    td Цена
			    td Сумма
			    td
			    br
	    	tr.item
	    		td = f.text_field :item_name
	    		td = f.text_field :unit
	    		td = f.text_field :price
	    		td = f.text_field :price_total
	    		td.del
	    		br
			tr.total
	    		td 
	    		td 
	    		td Итого
	    		td
	    		td.total_price
	    		br

	= f.submit 

app/views/invoices/show.html.slim
table width="772"
	 
        tr
	        td
        tr
       		td &nbsp;

        tr
          	td Образец заполнения платежного поручения
        tr
       		td &nbsp;

        tr
          	td
	        	table.table-bordered
					
		              tr
		                  td ИНН 1213123
		                  td КПП 12312312
		                  td  style="width: 54px;" rowspan="3" valign="bottom" Сч. №
		                  td  style="width: 218px;" rowspan="3" valign="bottom" 40702801999922211111
		              tr
		                  td colspan="2" Получатель</td>
             
              		  tr
		                  td width="440" colspan="2" Натуральный камень ОГРН 123123123
		              tr
		                  td colspan="2" Банк получателя
		                  td БИК
		                  td 049110123
		              tr
		                  td colspan="2" Банк Иж
		                  td Сч. №
		                  td valign="top" 30192919191919999991
		              
		            

        tr
          	td
            	h3 СЧЕТ № #{@invoice.id} от #{@invoice.created_at.strftime("%d/%m/%Y")}
            	
        
        tr
	        td
	            img src= "http://lorempixel.com/710/2"
        

        tr 
        	td &nbsp;

        tr
          	td
            	table
            		
	                	                    
	                	tr
	                    	td width="750" Покупатель: #{@invoice.customer.client}, ИНН: #{@invoice.customer.client_inn}, КПП: #{@invoice.customer.client_kpp}, ОГРН: #{@invoice.customer.client_ogrn}, Адрес: #{@invoice.customer.client_adress}
	                    

       

        tr
          	td
            	table.table-bordered
            		

	                tr
	                    td width="20" №
	                    td width="340" Наименование товара
	                    td width="60" Единица изме-рения
	                    td width="50" Коли-чество
	                    td width="120" Цена
	                    td width="120" Сумма
	                tr
	                    td 1
	                    td = @invoice.item_name
	                    td усл.
	                    td = @invoice.unit
	                    td = @invoice.price
	                    td = @invoice.price_total
                

	                tr
	                    td.text-right colspan="5" Итого:
	                    td.border#text-right = @invoice.price_total
	                tr
	                    td.text-right colspan="5"Без налога (НДС)
	                    td.border#text-right -
	                tr
	                    td.text-right colspan="5" Всего к оплате:
	                    td.border#text-right #{@invoice.price_total}  
                
            

        tr
        	td &nbsp;

        tr
          	td Всего наименований 1, на сумму #{@invoice.price_total}           
          	

        tr
        	td #{RuPropisju.rublej(@invoice.price_total).mb_chars.capitalize}  00 коп.
        tr
        	td &nbsp;

        tr
          	td Руководитель предприятия_____________________ (Бунтов А.И.)
         

        tr
        	td &nbsp;
        tr
        	td &nbsp;

        tr
          	td Главный бухгалтер_____________________ (Бунтов А.И.)
      

app/views/invoices/show.pdf.slim
table width="772"
	 
        tr
	        td
        tr
       		td &nbsp;

        tr
          	td Образец заполнения платежного поручения
        tr
       		td &nbsp;

        tr
          	td
	        	table.table-bordered
					
		              tr
		                  td ИНН 1213123
		                  td КПП 12312312
		                  td  style="width: 54px;" rowspan="3" valign="bottom" Сч. №
		                  td  style="width: 218px;" rowspan="3" valign="bottom" 40702801999922211111
		              tr
		                  td colspan="2" Получатель</td>
             
              		  tr
		                  td width="440" colspan="2" Натуральный камень ОГРН 123123123
		              tr
		                  td colspan="2" Банк получателя
		                  td БИК
		                  td 049110123
		              tr
		                  td colspan="2" Банк Иж
		                  td Сч. №
		                  td valign="top" 30192919191919999991
		              
		            

        tr
          	td
            	h3 СЧЕТ № #{@invoice.num} от #{@invoice.date}
            	
        
        tr
	        td
	            img src= "http://lorempixel.com/710/2"
        

        tr 
        	td &nbsp;

        tr
          	td
            	table
            		
	                	                    
	                	tr
	                    	td width="750" Покупатель: #{@customers.client}, ИНН: #{@customers.client_inn}, КПП: #{@customers.client_kpp}, ОГРН: #{@customers.client_ogrn}, Адрес: #{@customers.client_adress}
	                    

       

        tr
          	td
            	table.table-bordered
            		

	                tr
	                    td width="20" №
	                    td width="340" Наименование товара
	                    td width="60" Единица изме-рения
	                    td width="50" Коли-чество
	                    td width="120" Цена
	                    td width="120" Сумма
	                tr
	                    td 1
	                    td = @invoice.item_name
	                    td усл.
	                    td = @invoice.unit
	                    td = @invoice.price
	                    td = @invoice.price_total
                

	                tr
	                    td.text-right colspan="5" Итого:
	                    td.border#text-right = @invoice.price_total
	                tr
	                    td.text-right colspan="5"Без налога (НДС)
	                    td.border#text-right -
	                tr
	                    td.text-right colspan="5" Всего к оплате:
	                    td.border#text-right #{@invoice.price_total}  
                
            

        tr
        	td &nbsp;

        tr
          	td Всего наименований 1, на сумму #{@invoice.price_total}           
          	

        tr
        	td #{RuPropisju.rublej(@invoice.price_total).mb_chars.capitalize}  00 коп.
        tr
        	td &nbsp;

        tr
          	td Руководитель предприятия_____________________ (Бунтов А.И.)
         

        tr
        	td &nbsp;
        tr
        	td &nbsp;

        tr
          	td Главный бухгалтер_____________________ (Бунтов А.И.)
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crm3f</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>